spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice1?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    
    config:
    activate:
          on-profile: prod
server:
   port: 9000
          