
#spring.config.activate.on-profile=dev
#message=Dev message
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    
  config:
    activate:
          on-profile: dev
          
message: dev message         